#compatability package recommended in google api thing
import usr_credential_holder
import oauth2client.file.Storage

from __future__ 
import print_function
#lets me open spreadsheet by url :D
import gspread
from oauth2client.service_account import ServiceAccountCredentials
#pandas- lib for data analysis
import pandas as pd
#hold secretysecret file
import json

jsonobj = json()

store = oauth2client.file.Storage()



class MakingGoogleHappy:
#Is the oauth credential object the same as the oauth client id generated by google's API?
googautho = ServiceAccountCredentials.from_json_keyfile_name(home/maya/Downloads/SECRETS.json)
gspread.authorize(googautho)
#json.dump(ALLMYSECRETS)
#usinggspread = gspread.Client()
theform = gspread.open_by_url(https://docs.google.com/forms/d/16ranH8mONW_E940YF5Lzb57r_DmTCwXcZoO_ok0NDEg/edit)

#using Storage for json authorization instead of SignedJwtAssertionCredentials b/c the internet was angry; it's been discontinued
class UserCredentialExchange:
#put creds in holder
def putusercredentials(usr_credential_holder):
    store.locked_put(usr_credential_holder)
