from __future__ import print_function 

#compatability package recommended in google api thing
import usr_credential_holder
import oauth2client.file
#lets me open spreadsheet by url :D
import gspread
from oauth2client.service_account import ServiceAccountCredentials
#pandas- lib for data analysis
import pandas as pd
#hold secretysecret file
import json

#jsonobj = json()

#store = oauth2client.file.Storage()



	class MakingGoogleHappy:

		def __init__(self,jsonobj,store,googautho,theform):
			self.jsonobj = json()
			self.store = oauth2client.file.Storage()
			self.googautho = ServiceAccountCredentials.from_json_keyfile_name(home_maya_Downloads_SECRETS.json)
			#json.dump(ALLMYSECRETS)
			#usinggspread = gspread.Client()
			self.theform = gspread.open_by_url('https://docs.google.com/forms/d/16ranH8mONW_E940YF5Lzb57r_DmTCwXcZoO_ok0NDEg/edit')
			#Is the oauth credential object the same as the oauth client id generated by google's API?
			#googautho = ServiceAccountCredentials.from_json_keyfile_name(home_maya_Downloads_SECRETS.json)
	gspread.authorize(googautho) 