#compatability package recommended in google api thing
import usr_credential_holder
import oauth2client.file.Storage

from __future__ 
import print_function
#lets me open spreadsheet by url :D
import gspread
#pandas- lib for data analysis
import pandas as pd
#hold secretysecret file
import json

jsonobj = json()

store = oauth2client.file.Storage()


#Might have to use json.dump and then do this, dunno yet. This is to tell google's API that it can trust me

class MakingGoogleHappy:
#Is the oauth credential object the same as the oauth client id generated by google's API?
googautho = gspread.authorize()
#json.dump(ALLMYSECRETS)
usinggspread = gspread.Client()
theform = usinggspread.open_by_url(https://docs.google.com/forms/d/16ranH8mONW_E940YF5Lzb57r_DmTCwXcZoO_ok0NDEg/edit)

#using Storage for json authorization instead of SignedJwtAssertionCredentials b/c the internet was angry; it's been discontinued
class CredentialExchangeUser:
#put creds in holder
def putusercredentials(usr_credential_holder):
    store.locked_put(usr_credential_holder)
